name: CI

on:
  push: #här skulle vi kunna ange specifika branches läs mer här: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#using-filters
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Klona repot in i GitHub Actions-runnern
      - uses: actions/checkout@v4

      # 2. Installera rätt Node-version i den här maskinen
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Installera dependencies exakt som i lockfilen
      - run: npm ci

      # 4. Kör lintern (Next.js har next lint inbyggt)
      - run: npm run lint

      # 5. Kör testerna (inkl. det som failar)
      - run: npm test
